- hosts: all
  become: yes
  vars:
    user_password: !vault |
                   $ANSIBLE_VAULT;1.1;AES256
                   34306631376265386131643235303963616131306632323736353935643231613762643431366364
                   6161656466363239386430333666623339643732636431350a633565636363663531343631343561
                   65396630636139353036343861343065663134623732656334653834366231393539643764663137
                   6665636138346639320a303963336335363865643363623934663837643137666534316263313936
                   3239
  roles:
    - demo_vault
