- hosts: all
  become: yes
  vars:
    user_password: !vault |
                   $ANSIBLE_VAULT;1.1;AES256
                   32633234303133373062666337396435363032373963306138636537666362363334633165363135
                   6564383665346663336136656663393966363933393732640a633965333965316233323462363936
                   32346530326238653538303138353433656532656566353636333265363761336563336336303336
                   3961353231353239370a313262636363343030646139326461306239353364306166366265663334
                   3230

  tasks:
    - name: debug
      debug:
        var: user_password
